coverage:
  precision: 0
  round: down
  status:
    project:
      default:
       threshold: 100
       if_no_uploads: success
       if_not_found: success
       if_ci_failed: success
    patch:
      default:
        enabled: no
        threshold: 30
        if_no_uploads: success
        if_not_found: success
        if_ci_failed: success
    changes: no

ignore:
 - "Pods/.*" # ignore pods from code coverage
 - "Libraries/.*" # ignore third party libraries from code coverage
 - "Test/.*" # ignore Tests from code coverage
