# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run test suit"
  lane :test do
    scan(
      scheme: "edX",
      workspace: "edX.xcworkspace",
      clean: true,
      devices: ["iPhone 8 (12.4)", "iPhone 8 (13.3)"]
    )
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(xcodeproj: "edX.xcodeproj")
    gym(workspace: "edX.xcworkspace", scheme: "edX")
    # upload_to_testflight
  end

  desc "Push a new beta build to for Staging"
  lane :stage do 
    apply_stage_properties
    build_ipa
  end

  def apply_stage_properties
    File.delete("../edx.properties") if File.exist?("../edx.properties")
    File.open("../edx.properties", "w") {|file| file.puts "edx.dir = '../edx-mobile-config/stage'" }
  end

  def apply_prod_properties
    File.delete("../edx.properties") if File.exist?("../edx.properties")
    File.open("../edx.properties", "w") {|file| file.puts "edx.dir = '../edx-mobile-config/prod'" }
  end

  def build_ipa
    increment_build_number(xcodeproj: "edX.xcodeproj")
    gym(
      workspace: "edX.xcworkspace", 
      scheme: "edX", 
      # export_xcargs: "-allowProvisioningUpdates",
      output_directory: "./build", 
      archive_path: "./archives"
      )
  end
end
